<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assignment" nsURI="http://www.example.org/assignment" nsPrefix="assignment">
  <eClassifiers xsi:type="ecore:EClass" name="AGVServer">
    <eOperations name="start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGV">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verlocity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPathIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AGVManager"/>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WareHouse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wareshouseMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="K"/>
  </eClassifiers>
</ecore:EPackage>
